# Generated by Django 4.1.7 on 2023-02-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=6)),
                ("item_name", models.CharField(max_length=40)),
                ("item_quantity", models.IntegerField(default=0)),
                ("item_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("item_discount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("order_id", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_id", models.CharField(max_length=6)),
                ("rest_id", models.CharField(max_length=6)),
                ("rest_name", models.CharField(max_length=40)),
                ("item_name", models.CharField(max_length=40)),
                ("item_desc", models.CharField(max_length=120)),
                ("item_type", models.CharField(max_length=10)),
                ("item_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("item_discount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("item_rating", models.IntegerField(default=0)),
                ("item_status", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=6)),
                ("rest_id", models.CharField(max_length=6)),
                ("order_date", models.DateField(null=True)),
                ("delivery_date", models.DateField(null=True)),
                ("user_id", models.CharField(max_length=6)),
                ("user_name", models.CharField(max_length=40)),
                ("contact_no", models.CharField(max_length=10)),
                ("station_code", models.CharField(max_length=5)),
                ("station_name", models.CharField(max_length=40)),
                ("train_no", models.CharField(max_length=8)),
                ("train_name", models.CharField(max_length=40)),
                ("coach_no", models.CharField(max_length=4)),
                ("seat_no", models.IntegerField(default=0)),
                ("order_status", models.CharField(max_length=15)),
                ("item_count", models.IntegerField(default=0)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("total_discount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=6)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("special_instruction", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rest_id", models.CharField(max_length=6)),
                ("rest_name", models.CharField(max_length=40)),
                ("rest_address", models.CharField(max_length=120)),
                ("rest_location_code", models.CharField(max_length=120)),
                ("contact_person", models.CharField(max_length=40)),
                ("contact_no", models.CharField(max_length=10)),
                ("rest_rating", models.IntegerField(default=0)),
                ("rest_status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_code", models.CharField(max_length=5)),
                ("station_name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Stops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_no", models.CharField(max_length=8)),
                ("stop_no", models.IntegerField(default=0)),
                ("station_code", models.CharField(max_length=5)),
                ("arrival_time", models.CharField(max_length=5)),
                ("departure_time", models.CharField(max_length=5)),
                ("halt", models.CharField(max_length=4)),
                ("day", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_no", models.CharField(max_length=8)),
                ("train_name", models.CharField(max_length=40)),
            ],
        ),
    ]
