# Generated by Django 4.1.7 on 2023-02-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Stops", new_name="Stop",),
    ]
