# Generated by Django 4.1.7 on 2023-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0002_rename_stops_stop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=6)),
                ("order_id", models.CharField(max_length=6)),
                ("payment_date", models.DateField(null=True)),
                ("payment_amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("payment_mode", models.CharField(max_length=10)),
                ("payment_ref", models.CharField(max_length=20)),
                ("payment_status", models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(old_name="Items", new_name="Item",),
        migrations.RemoveField(model_name="order", name="special_instruction",),
    ]
