# Generated by Django 4.1.7 on 2023-02-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0003_payment_rename_items_item_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Item", new_name="OrderItem",),
        migrations.RenameModel(old_name="Menu", new_name="RestMenu",),
    ]
