# Generated by Django 4.1.7 on 2023-02-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0004_rename_item_orderitem_rename_menu_restmenu"),
    ]

    operations = [
        migrations.AlterModelOptions(name="order", options={"ordering": ["order_id"]},),
        migrations.AlterModelOptions(
            name="orderitem", options={"ordering": ["item_id"]},
        ),
        migrations.AlterModelOptions(
            name="payment", options={"ordering": ["payment_id"]},
        ),
        migrations.AlterModelOptions(
            name="restaurant", options={"ordering": ["rest_name"]},
        ),
        migrations.AlterModelOptions(
            name="restmenu", options={"ordering": ["item_name"]},
        ),
        migrations.AlterModelOptions(
            name="station", options={"ordering": ["station_code"]},
        ),
        migrations.AlterModelOptions(
            name="stop", options={"ordering": ["train_no", "stop_no"]},
        ),
        migrations.AlterModelOptions(name="train", options={"ordering": ["train_no"]},),
        migrations.RemoveField(model_name="order", name="station_name",),
        migrations.RemoveField(model_name="order", name="train_name",),
        migrations.RemoveField(model_name="order", name="user_name",),
        migrations.RemoveField(model_name="restmenu", name="rest_name",),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("0", "Initial"),
                    ("1", "Payment Done"),
                    ("2", "Payment Failed"),
                    ("3", "Accepted"),
                    ("4", "Rejected"),
                    ("5", "Preparing Food"),
                    ("6", "Order Ready"),
                    ("7", "In Transit"),
                    ("8", "Delivered"),
                    ("9", "Delivery Failed"),
                    ("10", "Cancelled"),
                ],
                default="0",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="rest_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="station_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.station",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="train_no",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.train",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[("1", "Success"), ("0", "Failed")], default="0", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rest_location_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.station",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rest_name",
            field=models.CharField(help_text="Restaurant Name", max_length=40),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rest_status",
            field=models.CharField(
                choices=[("1", "Open"), ("0", "Closed")], default="1", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="restmenu",
            name="item_status",
            field=models.CharField(
                choices=[("1", "Available"), ("0", "Unavailable")],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="restmenu",
            name="rest_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="station_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.station",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="train_no",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restapp.train",
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_name",
            field=models.CharField(help_text="Train Name", max_length=40),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_no",
            field=models.CharField(help_text="Train No", max_length=8),
        ),
    ]
