# Generated by Django 4.1.7 on 2023-02-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_alter_train_train_name_alter_train_train_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name)', max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name)', max_length=200)),
                ('doj', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name)', max_length=200)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('i', 'Initiated'), ('a', 'Accepted'), ('s', 'Serviced'), ('r', 'Rejected'), ('c', 'Closed')], default='i', help_text='Service Status', max_length=1)),
                ('dos', models.DateField(blank=True, null=True)),
                ('fees', models.IntegerField(default=-1)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapp.customer')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapp.service')),
                ('serviced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapp.expert')),
            ],
            options={
                'ordering': ['service', 'booked_by', 'serviced_by'],
            },
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.AddField(
            model_name='expert',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapp.service'),
        ),
    ]
