# Generated by Django 4.1.7 on 2023-02-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_train'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='name',
            new_name='train_name',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='no',
            new_name='train_no',
        ),
    ]
