# Generated by Django 4.1.7 on 2023-02-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0010_rename_name_train_train_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Train',
        ),
    ]
