# Generated by Django 4.1.7 on 2023-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0011_delete_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(max_length=10)),
                ('train_name', models.CharField(help_text='(Train name)', max_length=200)),
            ],
        ),
    ]
