# Generated by Django 4.1.7 on 2023-02-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0014_order_restaurant_station_stop_restmenu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop", name="stop_no", field=models.CharField(max_length=2),
        ),
    ]
