# Generated by Django 4.1.7 on 2023-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0016_alter_restmenu_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restmenu",
            name="item_type",
            field=models.CharField(
                choices=[("0", "Veg"), ("1", "Non-Veg")], default="0", max_length=1
            ),
        ),
    ]
