# Generated by Django 4.1.7 on 2023-02-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0017_alter_restmenu_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="user_id",
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
