# Generated by Django 4.1.7 on 2023-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0018_restaurant_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="rest_type",
            field=models.CharField(
                choices=[("0", "Veg"), ("1", "Non-Veg")], default="0", max_length=1
            ),
        ),
    ]
