# Generated by Django 4.1.7 on 2023-02-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0020_alter_order_order_id_alter_orderitem_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop", name="day", field=models.CharField(max_length=5),
        ),
    ]
