# Generated by Django 4.1.7 on 2023-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0023_alter_appuser_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="user_role",
            field=models.CharField(
                choices=[("1", "customer"), ("2", "restaurant")],
                default=1,
                max_length=1,
            ),
        ),
    ]
