# Generated by Django 4.1.7 on 2023-02-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0025_restaurant_rest_owner"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurant", name="rest_owner",),
    ]
