# Generated by Django 4.1.7 on 2023-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0028_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="arrival_time",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="departure_time",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="halt",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
