# Generated by Django 4.1.7 on 2023-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0029_alter_stop_arrival_time_alter_stop_departure_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="arrival_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="departure_time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="halt",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
