# Generated by Django 4.1.7 on 2023-02-25 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0031_alter_restaurant_contact_no_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant", old_name="user_id", new_name="rest_owner",
        ),
    ]
