# Generated by Django 4.1.7 on 2023-02-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0033_alter_restaurant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="user_mobile",
            field=models.CharField(default=9836498100, max_length=10),
            preserve_default=False,
        ),
    ]
