# Generated by Django 4.1.7 on 2023-02-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0034_appuser_user_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser", name="user_id", field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="order", name="order_id", field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="order", name="rest_id", field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="order", name="user_id", field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item_id",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_id",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order_id",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rest_id",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="restmenu",
            name="menu_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="restmenu",
            name="rest_id",
            field=models.CharField(max_length=15),
        ),
    ]
