# Generated by Django 4.1.7 on 2023-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0035_alter_appuser_user_id_alter_order_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("0", "Initial"),
                    ("1", "Paid"),
                    ("2", "Pending"),
                    ("3", "Confirmed"),
                    ("4", "Rejected"),
                    ("5", "Preparing Food"),
                    ("6", "Order Ready"),
                    ("7", "In Transit"),
                    ("8", "Delivered"),
                    ("9", "Delivery Failed"),
                    ("10", "Cancelled"),
                ],
                default="0",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rest_owner",
            field=models.CharField(default="-", max_length=15),
        ),
    ]
