# Generated by Django 4.1.7 on 2023-03-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0036_alter_order_order_status_alter_restaurant_rest_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("0", "Initial"),
                    ("2", "Pending"),
                    ("3", "Confirmed"),
                    ("4", "Rejected"),
                    ("6", "Order Ready"),
                    ("7", "In Transit"),
                    ("8", "Delivered"),
                    ("9", "Delivery Failed"),
                    ("10", "Cancelled"),
                ],
                default="0",
                max_length=2,
            ),
        ),
    ]
